chore: don't checkout lfs due to GitHub limitation
Apparently, GitHub charges for Git-LFS. We can't use it over a certain 
size or times.
https://github.com/Pure-D/atom-ide-d/runs/1984108866#step:2:163
```
Fetching LFS objects
  /usr/bin/git lfs fetch origin refs/remotes/origin/bundle-dcd
  fetch: Fetching reference refs/remotes/origin/bundle-dcd
  batch response: This repository is over its data quota. Account 
responsible for LFS bandwidth should purchase more data packs to restore 
access.
  Error: error: failed to fetch some objects from 
'Pure-D/atom-ide-d.git/info/lfs'
  The process '/usr/bin/git' failed with exit code 2
  Waiting 20 seconds before trying again
```